site_name: Sigma Documentação

theme:
  name: material


nav: 
  - inicio: index.md
  - documentação do swagger: doc_swagger_&_Postman.md
  - documentação explicativa do backend: explicativo_backend.md
  - documentação explicativo do frontend: explicativo_frontend.md